apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-hh4c
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-hh4c
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-hh4c
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-hh4c
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-hh4c
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dnou-tenant/rhtap-demo-app/hacbs-test-project-hh4c@sha256:febd569810ec15edc642d15a732cd425ebace079492fa5806009054b05f70b6d
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
